root_dir = "./"

[window]
width = 1280
height = 720
title = "2048 Game"
chessboard_size = 5

[window.menu]
background_img_uri = "game/ui/assets/images/menu_background.jpg"
menu_font_uri = "game/ui/assets/fonts/Milky Mania.ttf"

[window.sing_player]
background_img_uri = "game/ui/assets/images/sing_plyaer_background.jpg"
task_font = "game/ui/assets/fonts/zhbtt.ttf"
goal = "20482"
chessboard_size = 5

[window.multi_player]
background_img_uri = "game/ui/assets/images/multi_background.jpg"
task_font = "game/ui/assets/fonts/zhbtt.ttf"

[window.online_player]
background_img_uri = "game/ui/assets/images/multi_background.jpg"
task_font = "game/ui/assets/fonts/zhbtt.ttf"
ip_address = "127.0.0.1"
port = "8888"
